### ISSUE TITLE
Extension doesn't pick up action

### ISSUE THREAD

**Issue by kian99** [babakks/vscode-juju-charmcraft-ide#13]
I think I'm seeing an unexpected error from the extension. It's reporting an "undefinedEvent" for an action.
The offending line is the following:
```
        # create-authorization-model action
        self.framework.observe(
            self.on.create_authorization_model_action,
            self._on_create_authorization_model_action,
        )
```
![Screenshot from 2023-10-12 11-04-16](https://github.com/babakks/vscode-juju-charmcraft-ide/assets/46668016/276c613c-84f1-4f48-a062-da35381cb463)

![Screenshot from 2023-10-12 11-04-35](https://github.com/babakks/vscode-juju-charmcraft-ide/assets/46668016/956c6466-51eb-4516-b568-7cd5ffe06c0e)

Inside actions.yaml 
```
create-authorization-model:
  description: |
    Creates the authorization model using the content of the
    specified file and returns the authorization model ID.
  params:
    model:
      type: string
      description: |
        The JSON string containing the authorization model.
  required: [model]
```
