### ISSUE TITLE
Fix parser diagnostics for `platforms` key in `charmcraft.yaml`

### ISSUE THREAD

**Issue by babakks** [babakks/vscode-juju-charmcraft-ide#31]
The `charmcraft.yaml` [reference][charmcraft] is not clear/correct about the `platforms` key. These issues need to be resolved:

[charmcraft]: https://juju.is/docs/sdk/charmcraft-yaml#heading--bases

1. The docs suggest a format like this:

  ```yaml
  platforms:
    ubuntu@22.04:amd64:
    ubuntu@24.04:amd64:

  # or 

  platforms:
  jammy:
    build-on: [ubuntu@22.04:amd64]
    build-for: [ubuntu@22.04:amd64]
  noble:
    build-on: [ubuntu@24.04:amd64]
    build-for: [ubuntu@24.04:amd64]
  ```
  
  But neither of these formats are accepted by the `charmcraft pack` command. For the first example, it expects the keys in the `platforms` map to be one of supported architecture. For the second example, it complains that the `build-on`/`build-for` sequence values are not one of supported architectures.

2. In the docs, it says when a key in the `platforms` map is one of the supported architectures, then the `build-for` field is optional. However, running `charmcraft pack` will only work if either both or none of `build-on` and `build-for` fields are assigned.

There is a `TODO` marker in the parser code to show where we need to change to fix this. Currently, the parser ignores what's in the docs and accepts what actually works with `charmcraft pack`.
